#!/bin/bash
LOG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/info.log"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

KASM_UID=$(id -u kasm)

# 安装KasmVNC
sudo apt install /var/apps/kasm-lxqt/target/server/kasmvncserver_bookworm_*.deb -y
log_msg "[INFO] KasmVNC Server 版本: $(dpkg-query -W -f='${Version}' kasmvncserver 2>/dev/null)"

log_msg "[INFO] 配置KasmVNC的Systemd服务..."
sudo tee "/etc/systemd/system/kasmvnc.service" > /dev/null <<EOF
[Unit]
Description=KasmVNC Server
After=network.target

[Service]
Type=forking
User=kasm
Group=kasm
Restart=always
RestartSec=3

Environment=DISPLAY=:1
Environment=HOME=/home/kasm
ExecStart=/usr/bin/kasmvncserver
ExecStop=/usr/bin/kasmvncserver -kill

Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

log_msg "正在创建 proxy 服务..."
sudo tee "/etc/systemd/system/kasm-client.service" > /dev/null <<EOF
[Unit]
Description=kasm-client
After=kasmvnc.service
Requires=kasmvnc.service

[Service]
Type=simple
User=kasm
Group=kasm
Restart=always
RestartSec=3

ExecStart=${TRIM_APPDEST}/server/kclient 

[Install]
WantedBy=multi-user.target
EOF

# 开机自启 Kasm 
sudo systemctl daemon-reload
sudo systemctl enable kasmvnc.service
sudo systemctl enable kasm-client.service

if [ "$EUID" -eq 0 ]; then
    exec runuser -u "kasm" -- "$0" "$@"
fi

log_msg "当前执行脚本的用户: $(whoami)" 
mkdir -p ~/.config/pulse/default.pa.d

cat > ~/.config/pulse/default.pa <<'EOF'
.include /etc/pulse/default.pa
.include /home/kasm/.config/pulse/default.pa.d/kasm.pa
EOF

# 配置 PulseAudio
sudo cat > "/home/kasm/.config/pulse/default.pa.d/kasm.pa" <<'EOF'
load-module module-null-sink sink_name=kasm_sink sink_properties=device.description=KasmAudio
load-module module-remap-source source_name=virtmic master=kasm_sink.monitor

set-default-sink kasm_sink
set-default-source virtmic
EOF

systemctl --user enable --now pulseaudio.service


mkdir ~/.vnc
# 创建Kasm用户
rm -f ~/.kasmpasswd
echo -e "${wizard_password}\n${wizard_password}\n" | kasmvncpasswd -u "${wizard_username}" -ow

# 创建kasm配置文件
cat > "$HOME/.vnc/kasmvnc.yaml" <<EOF
desktop:
  resolution:
    width: 1920
    height: 1080
  allow_resize: true

network:
  protocol: http
  interface: 127.0.0.1
  websocket_port: 6901
  use_ipv4: true
  use_ipv6: false

server:
  http:
    headers:
      - Cross-Origin-Embedder-Policy=require-corp
      - Cross-Origin-Opener-Policy=same-origin
    httpd_directory: /usr/share/kasmvnc/www
  advanced:
    kasm_password_file: ${HOME}/.kasmpasswd

logging:
  log_writer_name: all
  log_dest: logfile
  level: 100
EOF

# 启动桌面
kasmvncserver -select-de lxqt
kasmvncserver -kill :1

# 生成LXQt配置
cat > "$HOME/.vnc/xstartup" <<EOF
#!/bin/sh

unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export PULSE_SERVER=unix:/run/user/${KASM_UID}/pulse/native

exec startlxqt
EOF
chmod +x ~/.vnc/xstartup      

exit 0