#!/bin/bash
CURRENT_USER=$(getent passwd 1000 | cut -d: -f1)
if [ -z "${CURRENT_USER}" ]; then
    exit 1
fi

# 配置本地用户
HOME_DIR="/home/${CURRENT_USER}"
sudo mkdir "${HOME_DIR}"
sudo chown -R 1000:1001 "${HOME_DIR}"
sudo chmod 700 "${HOME_DIR}"



exit 0