#!/bin/bash
LOG_FILE="${TRIM_DATA_SHARE_PATHS%%:*}/info.log"

log_msg() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >> ${LOG_FILE}
}

# 安装KasmVNC
sudo apt install /var/apps/kasm-lxqt/target/server/kasmvncserver_bookworm_*.deb -y
log_msg "[INFO] KasmVNC Server 版本: $(dpkg-query -W -f='${Version}' kasmvncserver 2>/dev/null)"

log_msg "[INFO] 配置KasmVNC的Systemd服务..."
sudo tee "/etc/systemd/system/kasmvnc.service" > /dev/null <<EOF
[Unit]
Description=KasmVNC Server
After=network.target

[Service]
Type=forking
User=kasm
Group=kasm
Restart=always
RestartSec=3

Environment=DISPLAY=:1
ExecStart=/usr/bin/kasmvncserver
ExecStop=/usr/bin/kasmvncserver -kill

Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

log_msg "正在创建 proxy 服务..."
sudo chown -R kasm:kasm "${TRIM_APPDEST}"
sudo tee "/etc/systemd/system/kasm-client.service" > /dev/null <<EOF
[Unit]
Description=kasm-client
After=kasmvnc.service
Requires=kasmvnc.service

[Service]
Type=simple
User=kasm
Group=kasm
Restart=always
RestartSec=3

ExecStart=${TRIM_APPDEST}/server/kclient 

[Install]
WantedBy=multi-user.target
EOF

# 开机自启 Kasm 
sudo systemctl daemon-reload
sudo systemctl enable kasmvnc.service
sudo systemctl enable kasm-client.service

# 切换为kasm用户
if [ "$EUID" -eq 0 ]; then
    exec runuser -u kasm -- "$0" "$@"
fi

# 配置 PulseAudio
mkdir -p ~/.config/pulse
cat > ~/.config/pulse/default.pa <<'EOF'
.include /etc/pulse/default.pa

load-module module-null-sink sink_name=kasm_sink sink_properties=device.description=KasmAudio
load-module module-remap-source source_name=virtmic master=kasm_sink.monitor

set-default-sink kasm_sink
set-default-source virtmic
EOF

systemctl --user enable --now pulseaudio.service

# 配置 Kasm 账号
rm -f ~/.kasmpasswd
echo -e "${wizard_password}\n${wizard_password}\n" | kasmvncpasswd -u "${wizard_username}" -ow

# 创建kasm配置文件
mkdir ~/.vnc
cat > "$HOME/.vnc/kasmvnc.yaml" <<EOF
desktop:
  resolution:
    width: 1920
    height: 1080
  allow_resize: true

network:
  protocol: http
  interface: 127.0.0.1
  websocket_port: 6901
  use_ipv4: true
  use_ipv6: false

  ssl:
    pem_certificate: /etc/ssl/certs/ssl-cert-snakeoil.pem
    pem_key: /etc/ssl/private/ssl-cert-snakeoil.key
    require_ssl: true

server:
  http:
    headers:
      - Cross-Origin-Embedder-Policy=require-corp
      - Cross-Origin-Opener-Policy=same-origin
    httpd_directory: /usr/share/kasmvnc/www
  advanced:
    kasm_password_file: ${HOME}/.kasmpasswd

logging:
  log_writer_name: all
  log_dest: logfile
  level: 100
EOF

# 启动桌面
kasmvncserver -select-de lxqt
kasmvncserver -kill :1

# 生成LXQt配置
cat > "$HOME/.vnc/xstartup" <<EOF
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS

export PULSE_SERVER=unix:/run/user/$(id -u)/pulse/native
exec startlxqt
EOF
chmod +x ~/.vnc/xstartup

# kclient 配置文件
cat > "$HOME/.vnc/kclient.yaml" <<EOF
subfolder: "/app/kasm-lxqt"
title: "KasmVNC Client"

fm_home: "/home/kasm"

vnc:
  proxy_target: "https://127.0.0.1:6901"

socket:  ${TRIM_APPDEST}/kclient.sock

audio:
  device: "kasm_sink.monitor"
  server: "/run/user/$(id -u)/pulse/native"

mic_socket: "/defaults/mic.sock"

max_upload_size: 200000000
EOF

exit 0