#!/bin/bash

case "$1" in
start)
    systemctl start kasm-client.service
    exit 0
    ;;
stop)
    systemctl stop kasm-client.service
    systemctl stop kasmvnc.service
    exit 0
    ;;

status)
    if systemctl is-active --quiet kasmvnc.service; then
        exit 0
    else
        exit 3
    fi
    ;;
*)
    exit 1
    ;;
esac